Incomplete JSON and Images were added
matias89/rc-shop-com-8 pull request #1
Opened 2019-10-21 22:42 UTC by luiscazzullo

2019-10-22 04:00 UTC, matias89 commented
@luiscazzullo you can add a prefix with text "WIP" in order to notify that the commit shouldn't be merged (WIP incomplet JSON and images were added)

2019-10-22 14:39 UTC, luiscazzullo commented
I finished the task 8

2019-10-22 17:33 UTC, matias89 requested changes

2019-10-22 17:33 UTC, matias89 commented on products/products.json
> +            "price-payment": 5000,
This is not a good way to create a property. Remember we can access to a property using `ObjectName.property` or `ObjectName['property']` but if you use "-" in property name, you can't call to a property using the second one way (`payment.price-payment` is not valid, you can't use "-" in a variable name)

2019-10-23 18:36 UTC, matias89 approved these changes

2019-10-23 18:36 UTC, merged